/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This class is used for Test Coverage of HttpCalloutWrapper.
* Mock Response form the Api will be mapped into corresponding Country_c Object Fields 
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Phalguni Pendyala
* @modifiedBy     
* @maintainedBy   
* @version        1.0
**/

@isTest
public class HttpCalloutWrapper_Test {

}